### PR TITLE
WIP: Channel implementation | DO NOT MERGE

### PR DESCRIPTION
**Pull request by TimonPost**
This PR is about providing an abstraction on top of different sockets. 

I thought a nice word to describe these abstractions would be "Channels".

Like we have :

- ReliableChannel
- UnreliableChannel
- ReliableOrderedChannel
- ReliableUnorderedChannel

They all implement `Channel` trait. Witch have to functions :

```
trait Channel
{
    fn send(&self, addr: SocketAddr, payload: &[u8]);
    fn recv(&self) -> Packet;
}
```

Then finally one struct that takes in a type of channel decides the right implementation to use for the enum type. Currently, this is called `CommunicationChannel`.

_For the user it will look like:_ 

```
        let ip_sender = SocketAddr::new(IpAddr::from_str("127.0.0.1").unwrap(), 12345);
        let ip_receiver = SocketAddr::new(IpAddr::from_str("127.0.0.1").unwrap(), 12346);

        let mut channel_sender = CommunicationChannel::new(ChannelType::ReliableUnordered, ip_sender);
        let mut channel_receiver = CommunicationChannel::new(ChannelType::ReliableUnordered, ip_receiver);

        let packet = channel_receiver.recv();
        channel_sender.send(ip_receiver, &[123]);

        let parsed = packet.unwrap().unwrap();
        assert_eq!(parsed.payload(), &[123]);
```

_The user only has to pass a ChannelType like to `CommunicationChannel`:_

```
pub enum ChannelType
{
    /// This type means:
    ///
    ///  1. Reliable.
    ///  2. No guarantee for delivery.
    ///  3. No guarantee for order.
    ///  4. Able to get dropped packets from the channel (udp with option to get dropped packets).
    ///
    /// Basically UDP but with a way to retrieve dropped packets.
    ReliableUnordered,
    /// This type means:
    ///
    /// 1. Unreliable
   ///  2. No guarantee for delivery.
   ///  3. No guarantee for order.
   ///  4. No way of getting dropped packet
   ///
   /// Basically just bare UDP
    Unreliable,
    
    // TODO: Reliable, guarantee for delivery (just bare tcp)
    // Reliable,
    // Todo: Unreliable, this represents an channel that will deliver everything in order. If packets do not arrive they will be stored and you can decide what to do with them.
    // Sequenced,
}
```

### CODE REVIEW

**Comment by LucioFranco** [comment]
I don't know if this is the right approach. I don't want to have to open two sockets to get the features of reliable and unreliable. I think it would make more sense to have a packet type enum and have one channel that can accept any type of packet. If that makes sense?

```rust
        send_tx.send(ReliablePacket::new(some_byte_buf));

        // Or

        send_tx.send(UnreliablePacket::new(some_byte_buf));
```

**Comment by eaglgenes101** [comment]
@LucioFranco 

I think the functionality of deciding how to implement reliability strategies is better made a property of the channel implementation rather than the packet implementation. Making reliability properties a property of the packet would essentially entail turning the channel into an asynchronous reactor, as it would have to defer to the packet trait to decide when and how to deal with a packet that seems to have been lost in transit. Opening two different sockets for two different-reliability channels isn't so bad.

**Comment by TimonPost** [comment]
I agree with you @eaglgenes101! 

Think that it is better to setup different sockets than have one that will be used for all kinds of packets. Having different packets will have also impact on the packet size. Because then you have to add another field to the header of each packet describing what kind of packet it is. 

Think the good points about these abstractions are:

1. User does not care about a Packet type. 
2. User does not need to care about different Channels/sockets etc.
3. When creating a channel the user only cares about one enum type which will represent a ChannelType/delivery method. 
4. Logic for different delivery methods like UnreliableOrdered, Reliable, Unreliable will all be handled separately so we sperate concerns here. 
5. We can add fun methods to different channels so if the user wants more with a channel it could use a specific channel directly instead of the `CommunicationChannel`
6. The user only has to care about the data that needs to be sent which he can do with send(bytes)

If you look at the use case here, then would it occur that a client switches often between channels? Probably the user wants some kind of channel (packet delivery method) whereafter it will be used for some duration. The client would not need to send first a reliable packet then unreliable.

**Comment by LucioFranco** [comment]
@TimonPost @eaglgenes101 To my understanding, I've never heard of using multiple UDP ports one for reliable and one for not reliable. I could be wrong though. How I see it internally there should be one socket that just sends bytes down the line. The sending logic should go if this is an unreliable packet just send no need for ack/seq, the client receives it and doesn't worry about sending an ack back. If it's a reliable packet then we do all the ack logic. In my mind this makes more sense, requires less blocking threads and simplifies the logic.

> it would have to defer to the packet trait to decide when and how to deal with a packet that seems to have been lost in transit.
 
This should be handled by the underlying socket and socket state implementation, not the channel. In reality, an unreliable packet is just a reliable packet without all the logic.

How I see the use of this as an end user is something like:

```rust
// Some game code logic
send(ReliablePacket::new(SomeUpdateScoreValue));

// or lets say position of the pong ball changed and I want send that state change 
// to the client
send(UnreliablePacket::new(SomeUpdatedState));
```

As a user I don't want to think about carrying around multiple channels or methods of sending, I want one uniform way of doing both. 

Maybe I am missing the point here and an example usage that shows how the user would set up and use this API would be nice. 😄

**Comment by eaglgenes101** [comment]
> This should be handled by the underlying socket and socket state implementation, not the channel. 

Suppose I want my own reliability strategy for what I'm doing with my own packets. Then what? Do I have to cooperate with the channel and its implementation details to register a callback to determine how to respond to a lost packet, and then set up a timer for the packet? Write my own network channel completely from scratch just to support MyCustomReliability in addition to the pre-provided reliability strategies (as opposed to just implementing a new reliability strategy trait and constructing a stock network channel on top of it)? Or what? 

> In reality, an unreliable packet is just a reliable packet without all the logic.

A packet has no logic except as conferred to it by the ends (and the bare minimum needed by the intermediaries to shuttle it from one end to the other). Sooner or later we're going to want more out of our network protocol, and stuffing more packet metadata into each and every packet to accommodate for this extra logic doesn't sound like a good idea. At least not compared to figuring out this configuration during handshaking when the socket connects.

**Comment by LucioFranco** [comment]
@eaglgenes101 

> Suppose I want my own reliability strategy for what I'm doing with my own packets. Then what? Do I have to cooperate with the channel and its implementation details to register a callback to determine how to respond to a lost packet, and then set up a timer for the packet? Write my own network channel completely from scratch just to support MyCustomReliability in addition to the pre-provided reliability strategies (as opposed to just implementing a new reliability strategy trait and constructing a stock network channel on top of it)? Or what?

Users of this library shouldn't have to worry about a custom reliability implementation. That's the point of making this. If they need their own for their use case than they are most likely better off implementing their own networking crate etc.

> A packet has no logic except as conferred to it by the ends (and the bare minimum needed by the intermediaries to shuttle it from one end to the other). Sooner or later we're going to want more out of our network protocol, and stuffing more packet metadata into each and every packet to accommodate for this extra logic doesn't sound like a good idea. At least not compared to figuring out this configuration during handshaking when the socket connects.

My point is something else, to the end user a packet is a packet. They can decide how it *should* get there but they shouldn't be worried about any more details. Internally we have to apply certain logic but to the outside this shouldn't be as visible.

To me what I want in an abstract manner is this:
```rust
let (tx, rx) = amethyst_protocol::serve(some_addr)?;

tx.send(some_packet);

let another_packet = rx.recv();
```

It really should be that simple to the end user. I don't want to bind two sockets just to get reliable and unreliable communication because that isn't needed.

**Pull request closed without merging**
